import { test,expect } from '@playwright/test';
import { start,answer } from './helpers.js';
import { missions } from '../../docs/js/content/missions.js';
import AxeBuilder from '@axe-core/playwright';
test('ambientes reconhecíveis, interações locais e pistas preservadas',async({page})=>{
  await start(page);
  await expect(page.locator('.game-world')).toBeVisible();
  await expect(page.locator('.chat-message')).toContainText('BAÚ LENDÁRIO');
  await expect(page.locator('.requested-data')).toContainText('Senha da conta');
  await page.getByRole('button',{name:'Eventos',exact:true}).click();
  await expect(page.locator('.scene-nav-info')).toContainText('Evento');
  await expect(page.locator('.requested-data')).toBeVisible();
  await expect(page.locator('.xp-total')).toHaveText('0 XP');
  for(const d of ['identify','assess','decide'])await answer(page,missions[0],d);
  await page.getByRole('button',{name:'Próxima missão'}).click();
  await expect(page.locator('.social-feed')).toBeVisible();
  expect((await new AxeBuilder({page}).analyze()).violations).toEqual([]);
  await page.getByRole('button',{name:'Ver comentários'}).click();
  await expect(page.locator('.social-comments')).toContainText('autorizei');
  await page.getByRole('button',{name:'Simular curtida'}).click();
  await expect(page.getByRole('button',{name:'Simular curtida'})).toHaveAttribute('aria-pressed','true');
  for(const d of ['identify','assess','decide'])await answer(page,missions[1],d);
  await page.getByRole('button',{name:'Próxima missão'}).click();
  await expect(page.locator('.private-conversation')).toContainText('Não está nas suas amizades');
  expect((await new AxeBuilder({page}).analyze()).violations).toEqual([]);
  await page.getByRole('button',{name:'Ver perfil do remetente'}).click();
  await expect(page.locator('.sender-details')).toContainText('Identidade não confirmada');
  for(const d of ['identify','assess','decide'])await answer(page,missions[2],d);
  await page.getByRole('button',{name:'Próxima missão'}).click();
  await expect(page.locator('.event-banner')).toContainText('ITEM RARO');
  await expect(page.locator('.cross-platform')).toBeVisible();
  expect((await new AxeBuilder({page}).analyze()).violations).toEqual([]);
  await expect(page.locator('textarea,input[type=text],input[type=tel],input[type=password]')).toHaveCount(0);
});
